services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_NAME
      - APP_KEY
      - APP_ENV
      - APP_URL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD